CREATE OR REPLACE CORTEX ANALYST SEMANTIC VIEW BANKING.VARO_SEMANTIC_VIEW
   AS
   SELECT
       c.CUSTOMER_ID,
       c.FIRST_NAME,
       c.LAST_NAME,
       c.EMAIL,
       c.DATE_OF_BIRTH,
       c.INCOME,
       c.OCCUPATION,
       a.ACCOUNT_ID,
       a.ACCOUNT_TYPE,
       a.BALANCE,
       a.INTEREST_RATE AS ACCOUNT_INTEREST_RATE,
       a.OPEN_DATE,
       a.STATUS AS ACCOUNT_STATUS,
       t.TRANSACTION_ID,
       t.TRANSACTION_TYPE,
       t.AMOUNT,
       t.TRANSACTION_DATE,
       t.DESCRIPTION,
       t.CATEGORY,
       t.IS_FRAUD,
       l.LOAN_ID,
       l.LOAN_TYPE,
       l.LOAN_AMOUNT,
       l.INTEREST_RATE AS LOAN_INTEREST_RATE,
       l.TERM_MONTHS,
       l.START_DATE,
       l.STATUS AS LOAN_STATUS,
       cc.CARD_ID,
       cc.CREDIT_LIMIT,
       cc.CURRENT_BALANCE,
       cc.DUE_DATE,
       cc.MIN_PAYMENT,
       cc.INTEREST_RATE AS CARD_INTEREST_RATE,
       cc.ISSUE_DATE,
       cc.STATUS AS CARD_STATUS,
       fd.FRAUD_ID,
       fd.FRAUD_TYPE,
       fd.RISK_SCORE,
       fd.DETECTION_DATE,
       fd.STATUS AS FRAUD_STATUS
   FROM BANKING.CUSTOMERS c
   LEFT JOIN BANKING.ACCOUNTS a ON c.CUSTOMER_ID = a.CUSTOMER_ID
   LEFT JOIN BANKING.TRANSACTIONS t ON a.ACCOUNT_ID = t.ACCOUNT_ID
   LEFT JOIN BANKING.LOANS l ON c.CUSTOMER_ID = l.CUSTOMER_ID
   LEFT JOIN BANKING.CREDIT_CARDS cc ON c.CUSTOMER_ID = cc.CUSTOMER_ID
   LEFT JOIN BANKING.FRAUD_DETECTION fd ON t.TRANSACTION_ID = fd.TRANSACTION_ID;
