-- Create Semantic View for Cortex Analyst with proper facts, dimensions, metrics
CREATE OR REPLACE SEMANTIC VIEW BANKING.VARO_SEMANTIC_VIEW AS
WITH
  FACTS AS (
    SELECT
      'Transactions' AS FACT_NAME,
      'BANKING.TRANSACTIONS' AS TABLE_NAME,
      'TRANSACTION_ID' AS PRIMARY_KEY
  ),
  DIMENSIONS AS (
    SELECT
      'CUSTOMER_ID' AS DIMENSION_NAME,
      'STRING' AS TYPE,
      'BANKING.CUSTOMERS' AS TABLE_NAME,
      'Customer identifier' AS DESCRIPTION
    UNION ALL
    SELECT 'ACCOUNT_TYPE' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.ACCOUNTS' AS TABLE_NAME, 'Type of account (Checking/Savings)' AS DESCRIPTION
    UNION ALL
    SELECT 'TRANSACTION_TYPE' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Type of transaction (Deposit/Withdrawal/Transfer)' AS DESCRIPTION
    UNION ALL
    SELECT 'CATEGORY' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Transaction category (e.g., Groceries)' AS DESCRIPTION
    UNION ALL
    SELECT 'LOAN_TYPE' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.LOANS' AS TABLE_NAME, 'Type of loan (Personal/Auto/Mortgage)' AS DESCRIPTION
    UNION ALL
    SELECT 'OCCUPATION' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.CUSTOMERS' AS TABLE_NAME, 'Customer occupation' AS DESCRIPTION
    UNION ALL
    SELECT 'FRAUD_TYPE' AS DIMENSION_NAME, 'STRING' AS TYPE, 'BANKING.FRAUD_DETECTION' AS TABLE_NAME, 'Type of fraud (e.g., Unauthorized)' AS DESCRIPTION
    UNION ALL
    SELECT 'TRANSACTION_DATE' AS DIMENSION_NAME, 'TIMESTAMP' AS TYPE, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Date of transaction' AS DESCRIPTION
    -- Add more dimensions as needed
  ),
  METRICS AS (
    SELECT
      'Total Balance' AS METRIC_NAME,
      'SUM(BALANCE)' AS EXPRESSION,
      'BANKING.ACCOUNTS' AS TABLE_NAME,
      'Total account balance' AS DESCRIPTION
    UNION ALL
    SELECT 'Transaction Amount' AS METRIC_NAME, 'SUM(AMOUNT)' AS EXPRESSION, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Sum of transaction amounts' AS DESCRIPTION
    UNION ALL
    SELECT 'Transaction Count' AS METRIC_NAME, 'COUNT(*)' AS EXPRESSION, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Number of transactions' AS DESCRIPTION
    UNION ALL
    SELECT 'Average Income' AS METRIC_NAME, 'AVG(INCOME)' AS EXPRESSION, 'BANKING.CUSTOMERS' AS TABLE_NAME, 'Average customer income' AS DESCRIPTION
    UNION ALL
    SELECT 'Fraud Count' AS METRIC_NAME, 'COUNT(IF(IS_FRAUD = TRUE, 1, NULL))' AS EXPRESSION, 'BANKING.TRANSACTIONS' AS TABLE_NAME, 'Number of fraudulent transactions' AS DESCRIPTION
    UNION ALL
    SELECT 'Loan Amount' AS METRIC_NAME, 'SUM(LOAN_AMOUNT)' AS EXPRESSION, 'BANKING.LOANS' AS TABLE_NAME, 'Total loan amounts' AS DESCRIPTION
    -- Add more metrics as needed
  );
