USE SCHEMA BANKING;

   CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION FRAUD_MODEL (
       INPUT_DATA => SYSTEM$QUERY_REFERENCE('SELECT AMOUNT, TRANSACTION_TYPE, CATEGORY, TRANSACTION_DATE, IS_FRAUD FROM BANKING.TRANSACTIONS WHERE IS_FRAUD IS NOT NULL'),
       TARGET_COLNAME => 'IS_FRAUD',
       CONFIG_OBJECT => {'evaluate': TRUE}
   );

   -- Optional: View evaluation metrics
   CALL FRAUD_MODEL!SHOW_EVALUATION_METRICS();

   -- Optional: View feature importance
   CALL FRAUD_MODEL!SHOW_FEATURE_IMPORTANCE();
